CREATE TABLE IF NOT EXISTS platform_users (
  idPlatformUser INT AUTO_INCREMENT PRIMARY KEY,
  idUser INT NOT NULL,
  role ENUM('SUPER_ADMIN', 'SUPPORT', 'ANALYST') NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT uk_platform_users_idUser UNIQUE (idUser),
  CONSTRAINT fk_platform_users_user
    FOREIGN KEY (idUser)
    REFERENCES users(idUser)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
